# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7477d64a8c302de47c16c4fc8f43c93871e66c6b8a21759807893025ca99ebdbe39ea9a28429aefeb10a79a5e6689218563abc2c5d4a85b2839af7c82b72ae1

test:
  secret_key_base: 66a5696fb2e06186fbeeaa8393b3ac162a19ba88dae84470e49416acc7945b83bce56bcdb0cb285da8bde4dd8a8b182ee6819723752b5b4867191342de3a04f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
